### ISSUE TITLE
File Meta Info

### ISSUE THREAD

**Issue by jhorback** [jhorback/harbor#128]
- [ ] Extract meta information from file uploads
- [ ] Add this meta information to the file storage
- [ ] Add a poster field from converting the picture to base64

**jsmediatags on NPMORG**
Can use this to pull meta data

https://www.npmjs.com/package/jsmediatags
https://github.com/aadsm/jsmediatags

There is an example of how to convert the picture to a base64 string
Can convert that and add a thumbSrc or poster
- title
- artist
- album
- year
- comment
- track
- genre
- picture
- lyrics
