### ISSUE TITLE
Sync Figma, CSS, and MD styles for a UDS

### ISSUE THREAD

**Issue by jhorback** [jhorback/harbor#20]
Update color and text styles in Figma to sync with the Harbor CSS styles and cross reference these with the Material Design principles.

Goal for a universal design system to make sure things sync up from a wireframe and dev perspective.

**Tasks**
- [ ] Figma styles updated
- [ ] CSS files created
- [ ] Layout grids in Figma created

**Comment by jhorback** [comment]
Studying Material Design 3 - will try to base Harbor off of this. Studying Color and Typography first.

The new MD web components are underway but will likely take some time to be release:
https://github.com/material-components/material-web

**Comment by jhorback** [comment]
Done
