### ISSUE TITLE
Create new environment checklist (push to production)

### ISSUE THREAD

**Issue by jhorback** [jhorback/harbor#208]
Do this while setting up a new environment: harbor-prod

- [x] Create github issue type for "New Environment"
- [x] Build this list when attempting to stand up a harbor production site (larisa)
- [x] Fix other github actions since .env file is now in .gitignore

**Goals**
* One github workflow file
* No differences between prod branches
  * Need to use vars on npm build?
