### ISSUE TITLE
Create production release checklist

### ISSUE THREAD

**Issue by jhorback** [jhorback/harbor#209]
Create new github issue type for "Production Release"

May be as simple as merging branches so the checklist would be small.

- [x]  Production releases will likely be a merge from master to a named branch
- [x]  Each time merging, likely want to tag that merge with the harbor version
- [x] Check theme setting (define what this means)

**Comment by jhorback** [comment]
This does not need a checklist now since the deployment is simply merging into master.
This will happen when creating a release.
